FROM node:16-slim

# set up workdir
RUN mkdir /api
WORKDIR /api

# install dependencies
RUN npm install -g npm@latest
COPY api/package*.json ./
RUN npm install

# build
COPY api .
RUN npm run build

# exposing
ENV HOST=0.0.0.0 PORT=3000
EXPOSE ${PORT}

# run
CMD ["node", "."]