version: '3'
services:
  proxy:
    container_name: proxy
    image: jungesmuensterschwarzach/jma-proxy:local
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - jenkins
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /var/data/mysql/secrets/root_pass
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${JMA_DATABASE}:/var/lib/mysql
      - ${MYSQL_SECRETS}:/var/data/mysql/secrets
    networks:
      - jenkins
  jma-app:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./app:/app
      - /app/node_modules
  jma-webservice:
    volumes:
      - ./webservice:/var/www/html
    profiles:
      - donotstart
  jma-cron:
    volumes:
      - ./webservice:/var/www/html
    profiles:
      - donotstart
  jma-api:
    container_name: jma-api
    image: jungesmuensterschwarzach/jma-api:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    volumes:
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
    networks:
      jenkins:
        ipv4_address: 172.16.1.242
  jma-phpmyadmin:
    container_name: jma-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: ${JMA_BASE_URL}/phpmyadmin
      MYSQL_ROOT_PASSWORD_FILE: /var/data/mysql/secrets/root_pass
      MEMORY_LIMIT: 1024M
      UPLOAD_LIMIT: 1024M
    restart: always
    volumes:
      - ${MYSQL_SECRETS}:/var/data/mysql/secrets
    networks:
      jenkins:
        ipv4_address: 172.16.1.30
  jma-database-backup-updater:
    profiles:
      - donotstart
networks:
  jenkins:
    external: true