FROM node:lts-alpine
RUN apk add git
WORKDIR /api
ENV PATH /api/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY ./api ./api
COPY ./commons ./commons
ENTRYPOINT ["npm", "run", "start-api"]