version: '3'
services:
  jma-database-backup-updater:
    container_name: jma-database-backup-updater
    image: jungesmuensterschwarzach/jma-database-backup-updater:latest
    build:
      context: .
      dockerfile: Dockerfile.database_backup_updater
    environment:
      JMA_BUILD_TYPE: ${JMA_BUILD_TYPE}
    restart: on-failure
    volumes:
      - ${JMA_IMAGES}:/workspace/storedImages
      - ./tools/database_update_scripts:/workspace/database_update_scripts
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
  jma-app:
    container_name: jma-app
    image: jungesmuensterschwarzach/jma-app:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.app.${JMA_BUILD_TYPE}
    restart: always
  jma-webservice:
    container_name: jma-webservice
    image: jungesmuensterschwarzach/jma-webservice:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.webservice
    restart: always
    volumes:
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
      - ${JMA_IMAGES}:/var/www/html/storedImages