version: '3'
services:
  proxy:
    container_name: proxy
    image: jenkinsluckev/jma-proxy:local
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - jenkins
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /var/data/mysql/secrets/root_pass
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - jma-database-data:/var/lib/mysql
      - jma-database-secrets:/var/data/mysql/secrets
    networks:
      - jenkins
  jma-app:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./app:/app
      - /app/node_modules
  jma-webservice:
    volumes:
      - ./webservice:/var/www/html
  jma-cron:
    volumes:
      - ./webservice:/var/www/html
    profiles:
      - donotstart
  jma-api:
    container_name: jma-api
    image: jenkinsluckev/jma-api:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.api
    profiles:
      - donotstart
    restart: always
    volumes:
      - jma-secrets-${JMA_BUILD_TYPE}:/var/data/secrets/jma
    networks:
      jenkins:
        ipv4_address: 172.16.1.242
  jma-database-backup-updater:
    profiles:
      - donotstart
volumes:
  jma-secrets-local:
    external: true
  jma-database-data:
    external: true
  jma-database-secrets:
    external: true
networks:
  jenkins:
    external: true