FROM openjdk:17-jdk-alpine as build
WORKDIR /var/data/AutomationTools
COPY ./tools/AutomationTools/ ./
RUN javac -cp libs/commons-io-2.8.0.jar:libs/commons-lang3-3.7.jar:libs/commons-text-1.3.jar:libs/json-simple-1.1.1.jar:libs/mysql-connector-java-8.0.12.jar -d build $(find -name "*.java")
RUN jar cvfm DatabaseBackupUpdater.jar deployment/manifest.database_backup_updater.mf -C build .

FROM openjdk:17-jdk-alpine as final
WORKDIR /workspace
RUN apk add --no-cache mysql-client git openssh mariadb-connector-c-dev
COPY --from=build /var/data/AutomationTools/DatabaseBackupUpdater.jar DatabaseBackupUpdater.jar
COPY --from=build /var/data/AutomationTools/libs ./libs
COPY ./tools/AutomationTools/deployment/.ssh /root/.ssh
COPY ./tools/AutomationTools/deployment/autorun.sh ./autorun.sh
CMD ["/bin/sh", "autorun.sh"]