version: '3'
services:
  jma-app:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./app:/app
      - /app/node_modules
  jma-webservice:
    volumes:
      - ./webservice:/var/www/html
  jma-dictionary-updater:
    container_name: jma-dictionary-updater
    depends_on:
      - jma-webservice
    image: jungesmuensterschwarzach/jma-dictionary-updater:latest
    build:
      context: .
      dockerfile: Dockerfile.dictionary_updater
    restart: on-failure
    volumes:
      - .:/workspace/project
  jma-phpmyadmin:
    container_name: jma-phpmyadmin
    depends_on:
      - jma-database
    image: phpmyadmin:latest
    environment:
      PMA_HOST: jma-database
      PMA_ABSOLUTE_URI: ${JMA_BASE_URL}/phpmyadmin
      MYSQL_ROOT_PASSWORD_FILE: /var/data/mysql/secrets/root_pass
    restart: always
    volumes:
      - ${MYSQL_SECRETS}:/var/data/mysql/secrets