version: '3'
services:
  jma-database-backup-updater:
    build:
      context: .
      dockerfile: Dockerfile.database_backup_updater
  jma-app:
    build:
      context: .
      dockerfile: Dockerfile.app.${JMA_BUILD_TYPE}
  jma-webservice:
    build:
      context: .
      dockerfile: Dockerfile.webservice
  jma-cron:
    build:
      context: .
      dockerfile: Dockerfile.cron