version: '3'
services:
  jma-database-backup-updater:
    container_name: jma-database-backup-updater
    image: jungesmuensterschwarzach/jma-database-backup-updater:latest
    build:
      context: .
      dockerfile: Dockerfile.database_backup_updater
    environment:
      JMA_BUILD_TYPE: ${JMA_BUILD_TYPE}
    restart: on-failure
    volumes:
      - ${JMA_IMAGES}:/workspace/storedImages
      - ./tools/database_update_scripts:/workspace/database_update_scripts
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
  jma-app:
    container_name: jma-app
    image: jungesmuensterschwarzach/jma-app:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.app.${JMA_BUILD_TYPE}
    restart: always
    networks:
      jenkins:
        ipv4_address: 172.16.1.240
  jma-webservice:
    container_name: jma-webservice
    image: jungesmuensterschwarzach/jma-webservice:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.webservice
    restart: always
    volumes:
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
      - ${JMA_IMAGES}:/var/www/html/storedImages
    networks:
      jenkins:
        ipv4_address: 172.16.1.241
  jma-api:
    container_name: jma-api
    image: jungesmuensterschwarzach/jma-api:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    networks:
      jenkins:
        ipv4_address: 172.16.1.242
  jma-cron:
    container_name: jma-cron
    image: jungesmuensterschwarzach/jma-cron:${JMA_BUILD_TYPE}
    build:
      context: .
      dockerfile: Dockerfile.cron
    restart: always
    volumes:
      - ${JMA_SECRETS}/${JMA_BUILD_TYPE}:/var/data/secrets/jma
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true