version: '3'
services:
  jma-database-backup-updater:
    container_name: jma-database-backup-updater
    image: jenkinsluckev/jma-database-backup-updater:latest
    environment:
      JMA_BUILD_TYPE: ${JMA_BUILD_TYPE}
    restart: on-failure
    volumes:
      - jma-imgs:/workspace/storedImages
      - jma-secrets-${JMA_BUILD_TYPE}:/var/data/secrets/jma
      - ./tools/database_update_scripts:/workspace/database_update_scripts
    networks:
      - jenkins
  jma-app:
    container_name: jma-app
    image: jenkinsluckev/jma-app:${JMA_BUILD_TYPE}
    restart: always
    networks:
      jenkins:
        ipv4_address: 172.16.1.240
  jma-webservice:
    container_name: jma-webservice
    image: jenkinsluckev/jma-webservice:${JMA_BUILD_TYPE}
    restart: always
    volumes:
      - jma-imgs:/var/www/html/storedImages
      - jma-secrets-${JMA_BUILD_TYPE}:/var/data/secrets/jma
    networks:
      jenkins:
        ipv4_address: 172.16.1.241
  jma-cron:
    container_name: jma-cron
    image: jenkinsluckev/jma-cron:${JMA_BUILD_TYPE}
    restart: always
    volumes:
      - jma-secrets-${JMA_BUILD_TYPE}:/var/data/secrets/jma
    networks:
      - jenkins
volumes:
  jma-imgs:
    external: true
  jma-secrets-dev:
    external: true
  jma-secrets-prod:
    external: true
networks:
  jenkins:
    external: true