export enum LogTags {
    ACCOUNT_DATA = "[ACCOUNT_DATA] \t",
    AUTHENTICATION = "[AUTHENTICATION] \t",
    CLIENT = "[CLIENT] \t",
    COOKIE_SERVICE = "[COOKIE_SERVICE] \t",
    DEPRECATION = "[DEPRECATION] \t",
    EVENTS = "[EVENTS] \t",
    NETWORK = "[NETWORK] \t",
    PUSH_SUBSCRIPTION = "[PUSH SUBSCRIPTION] \t",
    SERVER = "[SERVER] \t",
    SERVICE_WORKER = "[SERVICE_WORKER] \t",
    STORAGE_MANAGER = "[STORAGE_MANAGER] \t",
    THEME = "[THEME] \t"
}